apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::860300666219:user/terraform
      username: github-actions
      groups: 
        - system:masters